name: Deploy to Existing Compute Engine VM

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh instance-20250227-030817 --zone=asia-northeast3-a --command="
            # 백엔드 폴더 이동 또는 클론
            cd BE-Server || git clone https://github.com/WriteAgain/BE-Server.git && cd BE-Server
            git pull origin main
            
            # Java 21 설치 (이미 설치되어 있다면 무시됨)
            if ! java -version 2>&1 | grep '21.0.6'; then
              wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
              sudo dpkg -i jdk-21_linux-x64_bin.deb
              echo 'export JAVA_HOME=/usr/lib/jvm/jdk-21' >> ~/.bashrc
              echo 'export PATH=\$JAVA_HOME/bin:\$PATH' >> ~/.bashrc
              source ~/.bashrc
            fi
            java -version || echo ' Java 설치 실패'

            # Gradle 실행 권한 추가
            chmod +x ./gradlew

            # MySQL 8 다운로드 및 수동 설치
            wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.36-linux-glibc2.28-x86_64.tar.xz
            tar -xvf mysql-8.0.36-linux-glibc2.28-x86_64.tar.xz
            sudo mv mysql-8.0.36-linux-glibc2.28-x86_64 /usr/local/mysql
            sudo ln -s /usr/local/mysql/bin/* /usr/bin/

            # MySQL 데이터 디렉토리 설정 및 초기화
            sudo mkdir -p /usr/local/mysql/data
            sudo /usr/local/mysql/bin/mysqld --initialize --user=mysql || echo ' MySQL 초기화 실패'
            sudo /usr/local/mysql/bin/mysqld_safe --user=mysql &

            # MySQL root 사용자 설정 및 데이터베이스 초기화
            sleep 5  # MySQL이 실행될 시간을 줌
            sudo /usr/local/mysql/bin/mysqladmin -u root password 'ktbgroom' || echo ' MySQL root 비밀번호 설정 실패'
            
            # 데이터베이스 및 테이블 생성
            sudo /usr/local/mysql/bin/mysql -u root -p'ktbgroom' -e 'CREATE DATABASE IF NOT EXISTS writeagain;' || echo ' MySQL 데이터베이스 생성 실패'
            sudo /usr/local/mysql/bin/mysql -u root -p'ktbgroom' -e \"CREATE TABLE IF NOT EXISTS writeagain.users (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(255) NOT NULL UNIQUE,
              blog_type ENUM('velog', 'github', 'blog', 'tistory') NOT NULL
            );\" || echo ' MySQL 테이블 생성 실패'

            # 환경 변수 설정
            echo 'export SPRING_DATASOURCE_URL=jdbc:mysql://34.64.248.152:3306/writeagain?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_USERNAME=root' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_PASSWORD=ktbgroom' >> ~/.bashrc
            echo 'export AI_SERVER_URL=http://35.216.2.205' >> ~/.bashrc
            source ~/.bashrc

            # 백엔드 실행
            ./gradlew build
            nohup java -jar build/libs/*.jar > backend.log 2>&1 &
          "

