name: Deploy to Existing Compute Engine VM

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh was --zone=asia-northeast3-a --command="
            # 백엔드 폴더 이동 또는 클론
            cd BE-Server || git clone https://github.com/WriteAgain/BE-Server.git && cd BE-Server
            git pull origin main
            
            # Java 21 설치 (이미 설치된 경우 무시)
            if ! java -version 2>&1 | grep '21.0.6'; then
              sudo apt update
              sudo apt install -y openjdk-21-jdk
              echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64' >> ~/.bashrc
              echo 'export PATH=\$JAVA_HOME/bin:\$PATH' >> ~/.bashrc
              source ~/.bashrc
            fi
            java -version || echo ' Java 설치 실패'

            # Gradle 실행 권한 추가
            chmod +x ./gradlew

            # MySQL 8 설치 (이미 설치된 경우 무시)
            if ! mysql --version 2>&1 | grep 'Ver 8'; then
              sudo apt update
              sudo apt install -y mysql-server
              sudo systemctl start mysql
              sudo systemctl enable mysql
            fi

            # MySQL 설정 (root 비밀번호 설정 및 DB 생성)
            sudo mysql -e \"ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ktbgroom';\"
            sudo mysql -u root -p'ktbgroom' -e \"CREATE DATABASE IF NOT EXISTS writeagain;\"

            # 테이블 생성
            sudo mysql -u root -p'ktbgroom' -e \"USE writeagain;
              CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                username VARCHAR(255) NOT NULL UNIQUE,
                blog_type ENUM('velog', 'github', 'blog', 'tistory') NOT NULL
              );\"

            # 환경 변수 설정 (MySQL 8 URL 사용)
            echo 'export SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/writeagain?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_USERNAME=root' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_PASSWORD=ktbgroom' >> ~/.bashrc
            echo 'export AI_SERVER_URL=http://35.216.2.205' >> ~/.bashrc
            source ~/.bashrc

            # application.yml 자동 생성
            cat <<EOT > src/main/resources/application.yml
            spring:
              datasource:
                url: \${SPRING_DATASOURCE_URL}
                username: \${SPRING_DATASOURCE_USERNAME}
                password: \${SPRING_DATASOURCE_PASSWORD}
                driver-class-name: com.mysql.cj.jdbc.Driver

              jpa:
                database-platform: org.hibernate.dialect.MySQL8Dialect
                hibernate:
                  ddl-auto: update
                show-sql: true
                properties:
                  hibernate:
                    format_sql: true

            server:
              port: 8080

            ai:
              server:
                url: \${AI_SERVER_URL}
            EOT

            # 백엔드 실행
            ./gradlew build
            nohup java -jar build/libs/*.jar > backend.log 2>&1 &
          "
