name: Deploy to Existing Compute Engine VM

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh instance-20250227-030817 --zone=asia-northeast3-a --command="
            # 백엔드 폴더 이동 또는 클론
            cd BE-Server || git clone https://github.com/WriteAgain/BE-Server.git && cd BE-Server
            git pull origin main
            
            # Java 21 설치
            sudo apt update
            sudo apt install -y openjdk-21-jdk
            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
            export PATH=\$JAVA_HOME/bin:\$PATH
            echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64' >> ~/.bashrc
            echo 'export PATH=\$JAVA_HOME/bin:\$PATH' >> ~/.bashrc
            source ~/.bashrc
            
            # Gradle 실행 권한 추가
            chmod +x ./gradlew

            # MySQL 8.4.4 ARM 버전 설치 및 설정
            sudo apt install -y mysql-server
            sudo systemctl start mysql
            sudo systemctl enable mysql
            mysql -u root -e 'CREATE DATABASE IF NOT EXISTS writeagain;'
            mysql -u root -e \"CREATE TABLE IF NOT EXISTS writeagain.users (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(255) NOT NULL UNIQUE,
              blog_type ENUM('velog', 'github', 'blog', 'tistory') NOT NULL
            );\"

            # 환경 변수 설정 (GCP MySQL 및 AI 서버 IP 적용)
            echo 'export SPRING_DATASOURCE_URL=jdbc:mysql://34.64.248.152:3306/writeagain?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_USERNAME=root' >> ~/.bashrc
            echo 'export SPRING_DATASOURCE_PASSWORD=ktbgroom' >> ~/.bashrc
            echo 'export AI_SERVER_URL=http://35.216.2.205' >> ~/.bashrc
            source ~/.bashrc

            # 백엔드 실행
            ./gradlew build
            nohup java -jar build/libs/*.jar > backend.log 2>&1 &
          "
